# permissions for end users to view alertsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertsconfig-viewer-role
rules:
- apiGroups:
  - alertmanager.keikoproj.io
  resources:
  - alertsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alertmanager.keikoproj.io
  resources:
  - alertsconfigs/status
  verbs:
  - get
